name: Replicate Firebase
run-name: Replicate UBSA firebase
on:
  workflow_dispatch:
  schedule:
    # Run at 06:00, 12:00, 15:00 every day
    - cron: "0 * * * *"
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Set default branch name to `main`
        run: git config --global init.defaultBranch main
      - name: Check out main repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set Git config
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Ari Stassinopoulos (Automated)"
      - name: Replicate
        run: |
          curl https://ubsa-fb.firebaseio.com/schools/dublinHS.json > ./dublinHS.json
          echo `date -Iseconds` > ./latest_build.txt
          git add .
          git commit -m "Build at `date -Iseconds`"
          git push origin main
          exit 0
